name: app_install_checker
description: Check app is installed or not on Android and iOS devices.
version: 0.0.1
homepage: https://github.com/nanakomtmt/flutter_app_install_checker

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.nanakomtmt.app_install_checker
        pluginClass: AppInstallCheckerPlugin
      ios:
        pluginClass: AppInstallCheckerPlugin
